spring:
 application:
  name: portfolio-api

 datasource:
  url: jdbc:postgresql://localhost:5432/portfolio
  username: sunah
  password:

 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true

server:
 port: 8080

jwt:
 secret: portfolio-api-secret-keyportfolio-api-secret-keyportfolio-api-secret-key
 expiration: 86400000